name: oawidgets
channels:
  - openalea
  - defaults
  - conda-forge
dependencies:
  - python=2.7
  - mpfr<4
  - openalea.sconsx
  - openalea.misc
  - openalea.plantgl
  - nbsphinx
  - sphinx>=1.6
  - k3d
  - ipython
  - openalea.mtg
  - ipykernel
  - pandoc
  - nbconvert!=5.4
